### ISSUE TITLE
Snow footprints disappear on AMD but not other graphics cards

### ISSUE THREAD

**Issue by mokiros** [VirtualBrightPlayz/SLCloneIssues#11]
how to reproduce:
1. get nvidia gpu
2. run game
3. run through snow
4. snow footprints stay
5. replace nvidia gpu with amd gpu
6. run game
7. run through snow
8. snow footprints disappear
9. ???
10. profit

**Comment by Czekoloczek** [comment]
also happens on android
 ![Screenshot_20231228_232202_SLTwo.png](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/8a5f2521-3cca-47e8-94e0-b9e479424b72)

**Comment by Czekoloczek** [comment]
I can confrim this is fixed on Nvidia GPU BUT it's **not** fixed on android

pls reopen :3

**Comment by Czekoloczek** [comment]
![Screenshot_20231229_134400_SLTwo](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/34340f2d-798a-4828-8ce4-ab9dea23e0a6)

![Screenshot_20231228_232202_SLTwo](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/b4227dac-bd59-4b57-b797-e1367670daf1)

**Comment by Czekoloczek** [comment]
Android:
![Screenshot_20231229_134245_SLTwo](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/f6e5480e-138f-40e7-adfa-e06c5742d729)
Windows (Nvidia):
![obraz](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/da3d54d1-28ef-4e75-933e-9a4014426121)
