### ISSUE TITLE
[Enhancement] Ragdolls

### ISSUE THREAD

**Issue by Czekoloczek** [VirtualBrightPlayz/SLCloneIssues#32]
Ragdoll are funi :3

**Comment by VirtualBrightPlayz** [comment]
Completed for next patch.

**Comment by Czekoloczek** [comment]
@VirtualBrightPlayz i've killed a scientist
![image](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/b7d63fe1-5fdd-4d0d-a044-6a35a77712e6)
reopen this kekw
