### ISSUE TITLE
Keycard access info color bug

### ISSUE THREAD

**Issue by Czekoloczek** [VirtualBrightPlayz/SLCloneIssues#52]
I am on Windows using version 0.0.26
![obraz](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/dcc462ea-9eca-426b-8dd3-02ea62ff7512)

**Comment by VirtualBrightPlayz** [comment]
Won't fix, that text is for debugging use and will be removed at a later time.
