### ISSUE TITLE
Out of bounds as 173 on surface

### ISSUE THREAD

**Issue by Czekoloczek** [VirtualBrightPlayz/SLCloneIssues#55]
Windows v0.0.26
You can get on the fence if you jump from the railing as 173
![obraz](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/468c3bb7-e086-4b58-8696-a5af00aaa858)
and you can get out of bounds here
![obraz](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/3278ae0d-48ce-41d8-8401-6cfe0bc99127)
https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/bd54e1a3-33ae-4a35-9809-8b092d8f62bc

**Comment by TheMoogle** [comment]
I purposely made it so that you can get up on top of these as 173 as you can't actually get out truly of bounds.

**Comment by Czekoloczek** [comment]
> I purposely made it so that you can get up on top of these as 173 as you can't actually get out truly of bounds.

You can get out of bounds, it's hard but you can do it


https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/bd54e1a3-33ae-4a35-9809-8b092d8f62bc


(yes you can hear @VirtualBrightPlayz in the backgroudn when i told him you can get out of bounds :trollface:)
(if this wideo doesn't work for you then go here: https://drive.google.com/file/d/1aoIj2On9uL9M4zE-ZyoCAJnYNvkho7x5)

pls reopen :3

**Comment by Czekoloczek** [comment]
@TheMoogle

**Comment by TheMoogle** [comment]
Fixed in development builds
