### ISSUE TITLE
Language setting

### ISSUE THREAD

**Issue by Czekoloczek** [VirtualBrightPlayz/SLCloneIssues#6]
pls add a language setting :3

maybe change the file names to langpl.csv, langge,csv or just pl.csv, ge.csv (or just copy the SL translation system :trollface:)
I'm sure you'll work this out 👍🏻

**Comment by VirtualBrightPlayz** [comment]
Finished for next patch.

**Comment by Czekoloczek** [comment]
@VirtualBrightPlayz if you're done with this you need to also add the new translations to the original file for example the original file doesn't have the CI translations

**Comment by VirtualBrightPlayz** [comment]
https://virtualwebsite.net/files/SLTwo/translations.csv done
