### ISSUE TITLE
Add a soudtrack from megapatch II while joining a server

### ISSUE THREAD

**Issue by Czekoloczek** [VirtualBrightPlayz/SLCloneIssues#62]
Add "The Final Flash of Existence (Main Menu Intense)" by Jacek "Fragik" Rogal soundtrack while joining a server.
(this was added in megapatch II and removed after it for some reason)
https://hub.scpslgame.com/images/2/21/Menu_Intense.mp3

Comment by Dock Frankenstein:
> "the old menu at least had the feature where the main beat would drop when you were connecting. Still have no idea why they removed it. Made the game feel more polished back then than it is now"`

i would be grateful if you would try to recreate it

**Comment by Czekoloczek** [comment]
enhancement proposition by @ttyymmeekk on discord

**Comment by VirtualBrightPlayz** [comment]
https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/21286339/035a1ee1-6278-4172-bf8b-5026bf40f57d

**Comment by VirtualBrightPlayz** [comment]
I've since updated the playback to be less buggy.

https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/21286339/ef1bcb91-b11a-4df5-bb61-218f447966f9
