### ISSUE TITLE
Surface Door

### ISSUE THREAD

**Issue by Saskyc** [VirtualBrightPlayz/SLCloneIssues#68]
I am on (Windows/Linux/Android) using version 0.0.26, my issue is that this door is locked but larry can still walk thru them

![obrázek_2024-01-13_211451497](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/136163441/36a40a81-05d4-45c6-a2b4-b518114b58b0)

why is it a problem?

This is not a grey wall
![obrázek_2024-01-13_211514809](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/136163441/e43fe153-1510-47a7-a114-5aa663af5a49)

Out of map moment

![obrázek_2024-01-13_211528087](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/136163441/eecd3305-490a-4248-89da-04a3264f13c6)

**Comment by Saskyc** [comment]
I am on windows

**Comment by VirtualBrightPlayz** [comment]
Fixed for next patch.
