### ISSUE TITLE
Spectators can spectators

### ISSUE THREAD

**Issue by VirtualBrightPlayz** [VirtualBrightPlayz/SLCloneIssues#82]
I am on (Windows/Linux/Android) using version x.x.x, my issue is...

**Comment by Czekoloczek** [comment]
![image](https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/9562912c-9523-42be-9e40-789234008af4)
saving this

**Comment by Czekoloczek** [comment]
Spectators can spectate spectators 👎🏻 
Spectator can spectators 👍🏻
