### ISSUE TITLE
Voice chat is broken

### ISSUE THREAD

**Issue by Czekoloczek** [VirtualBrightPlayz/SLCloneIssues#98]
I am on (Windows/Linux/Android) using version 0.0.29, my issue is...

https://github.com/VirtualBrightPlayz/SLCloneIssues/assets/76474182/5efb4085-819e-416b-981a-e2e92c71074a

**Comment by VirtualBrightPlayz** [comment]
Fixed for next patch, needs testing.

**Comment by VirtualBrightPlayz** [comment]
Finally, it's fixed.
